# The aim of this GitHub workflow is to update the pipfile to sync with Codeflare-SDK release.
name: Sync ODH-notebooks with codeflare-sdk release
on:
  workflow_dispatch:
    inputs:
      upstream-repository-organization:
        required: true
        description: "Owner of target upstream notebooks repository used to open a PR against"
        default: "opendatahub-io"

      codeflare-repository-organization:
        required: true
        description: "Owner of origin notebooks repository used to open a PR"
        default: "project-codeflare"

      codeflare_sdk_release_version:
        required: true
        description: "Provide version of the Codeflare-SDK release"

env:
  BRANCH_NAME: main
  CODEFLARE_RELEASE_VERSION: ${{ github.event.inputs.codeflare_sdk_release_version }}
  UPDATER_BRANCH: odh-sync-updater-${{ github.run_id }}
  UPSTREAM_OWNER: ${{ github.event.inputs.upstream-repository-organization }}
  REPO_OWNER: ${{ github.event.inputs.codeflare-repository-organization }}
  REPO_NAME: notebooks
  GITHUB_TOKEN: ${{ secrets.CODEFLARE_MACHINE_ACCOUNT_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: |
            3.8
            3.9
