name: Release

on:
    workflow_dispatch:
        inputs:
            release-version:
              type: string
              required: true
              description: 'Version number (for example: 0.1.0)'

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            id-token: write  # This permission is required for trusted publishing
        steps:
            - name: Sync ODH Notebooks
              run: |
                gh workflow run odh-notebooks-sync.yml \
                  --repo sutaakar/codeflare-sdk \
                  --ref main \
                  --field upstream-repository-organization=opendatahub-io
                  --field codeflare-repository-organization=${{ github.event.inputs.project-codeflare }} \
                  --field codeflare_sdk_release_version=${{ github.event.inputs.release-version }}
              shell: bash
              env:
                  GITHUB_TOKEN: ${{ secrets.CODEFLARE_MACHINE_ACCOUNT_TOKEN }}
